# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute weighted Jaccard similarity
#'
#' @param A numeric matrix
#' @return The matrix with Jaccard similarity
wJaccard <- function(A) {
    .Call(`_assembly_wJaccard`, A)
}

